version: 1
appendOnly: true
labels:
  - label: 'dependencies'
    type: 'pull_request'
    authors:
      - 'pre-commit-ci[bot]'
      - 'dependabot[bot]'
      - 'renovate[bot]'
  - label: 'bugfix'
    type: 'pull_request'
    title: '(?i).*fix.*'
  - label: 'feature'
    type: 'pull_request'
    title: '(?i).*feat.*'
  - label: 'breaking-change'
    type: 'pull_request'
    title: '(?i).*breaking[ -_]change.*'
  - label: 'github-workflows'
    type: 'pull_request'
    title: '(?i).*(github[ -_]?actions?|workflow(s)?).*'
  - label: 'enhancement'
    type: 'pull_request'
    title: '(?i).*(enhance|improv(e|ement)).*'
  - label: 'documentation'
    type: 'pull_request'
    title: '(?i).*(docs|document|readme).*'
  - label: 'code-quality'
    type: 'pull_request'
    title: '(?i).*(lint|ruff|mypy|pytest|coverage|prek|type-?check|pre[ -_]?commit).*'
