// Sshwifty - A Web SSH client
//
// Copyright (C) 2019 Rui NI <nirui@gmx.com>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

package controller

//go:generate go run ./static_page_generater ../../.tmp/dist ./static_pages.go
//go:generate go fmt ./static_pages.go

// This file is generated by `go generate` at Wed, 07 Aug 2019 15:54:10 CST
// DO NOT EDIT!

import "github.com/niruix/sshwifty/application/controller/static_pages"

import "time"

var (
	staticPages = map[string]staticData{
		"13ec0eb5bdb821ff4930237d7c9f943f.woff2":                                   parseStaticData(static_pages.Static0()),
		"13efe6cbc10b97144a28310ebdeda594.woff":                                    parseStaticData(static_pages.Static1()),
		"1d6594826615607f6dc860bb49258acb.woff":                                    parseStaticData(static_pages.Static2()),
		"313a65630d341645c13e4f2a0364381d.woff":                                    parseStaticData(static_pages.Static3()),
		"35b07eb2f8711ae08d1f58c043880930.woff":                                    parseStaticData(static_pages.Static4()),
		"4357beb823a5f8d65c260f045d9e019a.woff2":                                   parseStaticData(static_pages.Static5()),
		"4fe0f73cc919ba2b7a3c36e4540d725c.woff":                                    parseStaticData(static_pages.Static6()),
		"50d75e48e0a3ddab1dd15d6bfb9d3700.woff":                                    parseStaticData(static_pages.Static7()),
		"59eb3601394dd87f30f82433fb39dd94.woff2":                                   parseStaticData(static_pages.Static8()),
		"5b4a33e176ff736a74f0ca2dd9e6b396.woff2":                                   parseStaticData(static_pages.Static9()),
		"6972f63e5242168cc5637e2771292ec0-android-chrome-144x144.png":              parseStaticData(static_pages.Static10()),
		"6972f63e5242168cc5637e2771292ec0-android-chrome-192x192.png":              parseStaticData(static_pages.Static11()),
		"6972f63e5242168cc5637e2771292ec0-android-chrome-256x256.png":              parseStaticData(static_pages.Static12()),
		"6972f63e5242168cc5637e2771292ec0-android-chrome-36x36.png":                parseStaticData(static_pages.Static13()),
		"6972f63e5242168cc5637e2771292ec0-android-chrome-384x384.png":              parseStaticData(static_pages.Static14()),
		"6972f63e5242168cc5637e2771292ec0-android-chrome-48x48.png":                parseStaticData(static_pages.Static15()),
		"6972f63e5242168cc5637e2771292ec0-android-chrome-512x512.png":              parseStaticData(static_pages.Static16()),
		"6972f63e5242168cc5637e2771292ec0-android-chrome-72x72.png":                parseStaticData(static_pages.Static17()),
		"6972f63e5242168cc5637e2771292ec0-android-chrome-96x96.png":                parseStaticData(static_pages.Static18()),
		"6972f63e5242168cc5637e2771292ec0-apple-touch-icon-114x114.png":            parseStaticData(static_pages.Static19()),
		"6972f63e5242168cc5637e2771292ec0-apple-touch-icon-120x120.png":            parseStaticData(static_pages.Static20()),
		"6972f63e5242168cc5637e2771292ec0-apple-touch-icon-144x144.png":            parseStaticData(static_pages.Static21()),
		"6972f63e5242168cc5637e2771292ec0-apple-touch-icon-152x152.png":            parseStaticData(static_pages.Static22()),
		"6972f63e5242168cc5637e2771292ec0-apple-touch-icon-167x167.png":            parseStaticData(static_pages.Static23()),
		"6972f63e5242168cc5637e2771292ec0-apple-touch-icon-180x180.png":            parseStaticData(static_pages.Static24()),
		"6972f63e5242168cc5637e2771292ec0-apple-touch-icon-57x57.png":              parseStaticData(static_pages.Static25()),
		"6972f63e5242168cc5637e2771292ec0-apple-touch-icon-60x60.png":              parseStaticData(static_pages.Static26()),
		"6972f63e5242168cc5637e2771292ec0-apple-touch-icon-72x72.png":              parseStaticData(static_pages.Static27()),
		"6972f63e5242168cc5637e2771292ec0-apple-touch-icon-76x76.png":              parseStaticData(static_pages.Static28()),
		"6972f63e5242168cc5637e2771292ec0-apple-touch-icon-precomposed.png":        parseStaticData(static_pages.Static29()),
		"6972f63e5242168cc5637e2771292ec0-apple-touch-icon.png":                    parseStaticData(static_pages.Static30()),
		"6972f63e5242168cc5637e2771292ec0-apple-touch-startup-image-1182x2208.png": parseStaticData(static_pages.Static31()),
		"6972f63e5242168cc5637e2771292ec0-apple-touch-startup-image-1242x2148.png": parseStaticData(static_pages.Static32()),
		"6972f63e5242168cc5637e2771292ec0-apple-touch-startup-image-1496x2048.png": parseStaticData(static_pages.Static33()),
		"6972f63e5242168cc5637e2771292ec0-apple-touch-startup-image-1536x2008.png": parseStaticData(static_pages.Static34()),
		"6972f63e5242168cc5637e2771292ec0-apple-touch-startup-image-320x460.png":   parseStaticData(static_pages.Static35()),
		"6972f63e5242168cc5637e2771292ec0-apple-touch-startup-image-640x1096.png":  parseStaticData(static_pages.Static36()),
		"6972f63e5242168cc5637e2771292ec0-apple-touch-startup-image-640x920.png":   parseStaticData(static_pages.Static37()),
		"6972f63e5242168cc5637e2771292ec0-apple-touch-startup-image-748x1024.png":  parseStaticData(static_pages.Static38()),
		"6972f63e5242168cc5637e2771292ec0-apple-touch-startup-image-750x1294.png":  parseStaticData(static_pages.Static39()),
		"6972f63e5242168cc5637e2771292ec0-apple-touch-startup-image-768x1004.png":  parseStaticData(static_pages.Static40()),
		"6972f63e5242168cc5637e2771292ec0-favicon-16x16.png":                       parseStaticData(static_pages.Static41()),
		"6972f63e5242168cc5637e2771292ec0-favicon-32x32.png":                       parseStaticData(static_pages.Static42()),
		"6972f63e5242168cc5637e2771292ec0-favicon.ico":                             parseStaticData(static_pages.Static43()),
		"6972f63e5242168cc5637e2771292ec0-firefox_app_128x128.png":                 parseStaticData(static_pages.Static44()),
		"6972f63e5242168cc5637e2771292ec0-firefox_app_512x512.png":                 parseStaticData(static_pages.Static45()),
		"6972f63e5242168cc5637e2771292ec0-firefox_app_60x60.png":                   parseStaticData(static_pages.Static46()),
		"6972f63e5242168cc5637e2771292ec0-manifest.json":                           parseStaticData(static_pages.Static47()),
		"6972f63e5242168cc5637e2771292ec0-manifest.webapp":                         parseStaticData(static_pages.Static48()),
		"7237b0744491024097d3d.css":                                                parseStaticData(static_pages.Static49()),
		"7237b0744491024097d3d.css.map":                                            parseStaticData(static_pages.Static50()),
		"7237b0744491024097d3d.js":                                                 parseStaticData(static_pages.Static51()),
		"73f0a88bbca1bec19fb1303c689d04c6.woff2":                                   parseStaticData(static_pages.Static52()),
		"83e114c316fcc3f23f524ec3e1c65984.woff":                                    parseStaticData(static_pages.Static53()),
		"8a96edbbcd9a6991d79371aed0b0288e.woff":                                    parseStaticData(static_pages.Static54()),
		"90d1676003d9c28c04994c18bfd8b558.woff2":                                   parseStaticData(static_pages.Static55()),
		"94008e69aaf05da75c0bbf8f8bb0db41.woff2":                                   parseStaticData(static_pages.Static56()),
		"DEPENDENCES.md":                                                           parseStaticData(static_pages.Static57()),
		"LICENSE.md":                                                               parseStaticData(static_pages.Static58()),
		"README.md":                                                                parseStaticData(static_pages.Static59()),
		"ad538a69b0e8615ed0419c4529344ffc.woff2":                                   parseStaticData(static_pages.Static60()),
		"b52fac2bb93c5858f3f2675e4b52e1de.woff2":                                   parseStaticData(static_pages.Static61()),
		"c599374e350aa7225ee3e8a114e8d8d7.svg":                                     parseStaticData(static_pages.Static62()),
		"c73eb1ceba3321a80a0aff13ad373cb4.woff":                                    parseStaticData(static_pages.Static63()),
		"cc2fadc3928f2f223418887111947b40.woff":                                    parseStaticData(static_pages.Static64()),
		"d26871e8149b5759f814fd3c7a4f784b.woff2":                                   parseStaticData(static_pages.Static65()),
		"d3b47375afd904983d9be8d6e239a949.woff":                                    parseStaticData(static_pages.Static66()),
		"e8eaae902c3a4dacb9a5062667e10576.woff2":                                   parseStaticData(static_pages.Static67()),
		"ea4853ff509fe5f353d52586fcb94e20.svg":                                     parseStaticData(static_pages.Static68()),
		"f5902d5ef961717ed263902fc429e6ae.woff":                                    parseStaticData(static_pages.Static69()),
		"f75569f8a5fab0893fa712d8c0d9c3fe.woff2":                                   parseStaticData(static_pages.Static70()),
		"index.html":                                                               parseStaticData(static_pages.Static71()),
		"manifest.json":                                                            parseStaticData(static_pages.Static72()),
		"robots.txt":                                                               parseStaticData(static_pages.Static73()),
	}
)

// parseStaticData parses result from a static file returner and generate
// a new `staticData` item
func parseStaticData(
	fileStart int,
	fileEnd int,
	compressedStart int,
	compressedEnd int,
	contentHash string,
	compressedHash string,
	creation time.Time,
	data []byte,
) staticData {
	return staticData{
		data:          data[fileStart:fileEnd],
		dataHash:      contentHash,
		compressd:     data[compressedStart:compressedEnd],
		compressdHash: compressedHash,
		created:       creation,
	}
}
